---
# Dragon is a Linux x86_64 binary - needs box64 to run
- name: Synchronize Dragon
  ansible.posix.synchronize:
    src: files/extra_engines/dragon/
    dest: /opt/picochess/engines/{{ ansible_architecture }}/dragon/

- name: Ensure "name=Dragon" is in dragon section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: dragon/dragon-linux
    option: name
    value: Dragon
    state: present

- name: Ensure "small=dragon" is in dragon section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: dragon/dragon-linux
    option: small
    value: dragon
    state: present

- name: Ensure "medium=Dragon" is in dragon section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: dragon/dragon-linux
    option: medium
    value: Dragon
    state: present

- name: Ensure "large=Dragon" is in dragon section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: dragon/dragon-linux
    option: large
    value: Dragon
    state: present

- name: Ensure "elo=3000" is in dragon section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: dragon/dragon-linux
    option: elo
    value: 3000
    state: present

- name: Ensure "ponder/brain=n" is in dragon section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: dragon/dragon-linux
    option: ponder/brain
    value: n
    state: present
