---
- name: Synchronize Pedone 3.0
  ansible.posix.synchronize:
    src: files/extra_engines/pedone/
    dest: /opt/picochess/engines/{{ ansible_architecture }}/pedone/

- name: Ensure "name=Pedone 3.0" is in pedone section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: pedone/Pedone_armv8
    option: name
    value: Pedone 3.0
    state: present
    create: false

- name: Ensure "small=Pedone" is in pedone section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: pedone/Pedone_armv8
    option: small
    value: Pedone
    state: present
    create: false

- name: Ensure "medium=Pedone3" is in pedone section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: pedone/Pedone_armv8
    option: medium
    value: Pedone3
    state: present
    create: false

- name: Ensure "large=Pedone 3.0" is in pedone section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: pedone/Pedone_armv8
    option: large
    value: Pedone 3.0
    state: present
    create: false

- name: Ensure "elo=3000" is in pedone section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: pedone/Pedone_armv8
    option: elo
    value: 3000
    state: present
    create: false

- name: Ensure "levels=11" is in pedone section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: pedone/Pedone_armv8
    option: levels
    value: 11
    state: present
    create: false

- name: Ensure "ponder/brain=n" is in pedone section
  community.general.ini_file:
    path: /opt/picochess/engines/{{ ansible_architecture }}/favorites.ini
    section: pedone/Pedone_armv8
    option: ponder/brain
    value: n
    state: present
    create: false
