---
- name: Git config
  ansible.builtin.shell: git config --global --add safe.directory /opt/picochess
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Clone https://github.com/gkalab/picochess
  ansible.builtin.git:
    repo: https://github.com/gkalab/picochess
    version: master
    dest: /opt/picochess
    force: true

- name: Synchronize picochess files
  ansible.posix.synchronize:
    src: files/opt/picochess/
    dest: /opt/picochess/

- name: Ensure default engine is present in picochess.ini
  ansible.builtin.lineinfile:
    dest: /opt/picochess/picochess.ini
    regexp: '^engine ='
    line: 'engine = /opt/picochess/engines/{{ ansible_architecture }}/a-stockf'
    state: present

- name: Ensure default tutor engine is present in picochess.ini
  ansible.builtin.lineinfile:
    dest: /opt/picochess/picochess.ini
    regexp: '^tutor-engine ='
    line: 'tutor-engine = /opt/picochess/engines/{{ ansible_architecture }}/a-stockf'
    state: present

- name: Synchronize service definitions
  ansible.posix.synchronize:
    src: files/etc/systemd/system/
    dest: /etc/systemd/system/

# the bcrypt module requires Rust to compile on armv7
- name: Install Rust
  ansible.builtin.import_tasks: rust.yml
  when: ansible_architecture == "armv7l"

- name: Install PicoChess dependencies
  ansible.builtin.pip:
    requirements: /opt/picochess/requirements.txt

- name: Enable service picochess
  ansible.builtin.service:
    name: picochess
    enabled: true
