---
- name: Install PicoChessWeb
  hosts: picochess
  become: true

  tasks:
    - name: Setup system
      ansible.builtin.import_tasks: tasks/system.yml

    - name: Update hostname
      ansible.builtin.import_tasks: tasks/update_hostname.yml

    - name: Install PicoChess
      ansible.builtin.import_tasks: tasks/picochess.yml
      tags: picochess

    - name: Install games database
      ansible.builtin.import_tasks: tasks/gamesdb.yml
      tags: picochess

    - name: Install opening book server
      ansible.builtin.import_tasks: tasks/obooksrv.yml
      tags: picochess

    - name: Install voices
      ansible.builtin.import_tasks: tasks/voices.yml
      tags: picochess, voices

    - name: Install architecture dependent binaries/engines
      ansible.builtin.import_tasks: tasks/architecture.yml
      tags: picochess, engines

    - name: Add splash screen
      ansible.builtin.import_tasks: tasks/splash.yml
      tags: splash

    - name: Reboot
      ansible.builtin.import_tasks: tasks/reboot.yml
